bump v0.1.1
FuelLabs/action-fuel-toolchain pull request #31
Opened 2022-06-23 06:45 UTC by binggh

Depends on #30

2022-06-23 17:54 UTC, adlerjohn approved these changes

2022-06-23 17:55 UTC, adlerjohn requested changes
Ah wait can you also update the readme

2022-06-24 00:35 UTC, binggh commented
> Ah wait can you also update the readme

Thanks for the catch - fixed now

2022-06-24 01:00 UTC, adlerjohn approved these changes

2022-06-24 01:08 UTC, merged